GeneticAlgorithm: Chromosome.cpp DoubleGene.cpp GeneticAlgorithm.cpp IntegerGene.cpp Population.cpp Utilities.cpp
	g++ -Wall -Werror -pedantic -O2 --std=c++11 Chromosome.cpp DoubleGene.cpp GeneticAlgorithm.cpp IntegerGene.cpp Population.cpp Utilities.cpp -o GeneticAlgorithm

clean:
	rm -vf GeneticAlgorithm *~
